[project]
title = "lsst-daf-butler"

[project.python]
package = "lsst-daf-butler"

[build]
clean = true

[sphinx]
extensions = [
    "sphinx_click"
]

[sphinx.intersphinx.projects]
astropy = "https://docs.astropy.org/en/stable"
python = "https://docs.python.org/3"
lsst = "https://pipelines.lsst.io/v/daily/"
click = "https://click.palletsprojects.com/en/stable"
