datastore:
  cls: lsst.daf.butler.datastores.s3Datastore.S3Datastore
  root: <butlerRoot>/datastore
  records:
    table: s3datastorerecords
  create: true
  templates:
    # valid_first and valid_last here are YYYYMMDD; we assume we'll switch to
    # MJD (DM-15890) before we need more than day resolution, since that's all
    # Gen2 has.
    default: "{collection:/}/{datasetType}.{component:?}/{tract:?}/{patch:?}/{label:?}/{abstract_filter:?}/{subfilter:?}/{physical_filter:?}/{visit:?}/{datasetType}_{component:?}_{tract:?}_{patch:?}_{label:?}_{abstract_filter:?}_{physical_filter:?}_{calibration_label:?}_{visit:?}_{exposure:?}_{detector:?}_{instrument:?}_{skymap:?}_{skypix:?}_{run}"
  formatters: !include formatters.yaml
