composites:
  # True: concrete composite (composites are disassembled);
  # False: virtual composite (composites are written monolithically).
  # default applies to all composites that are not explicitly mentioned
  # elsewhere.
  default: False
  # Use a dict rather than a list to allow easy merging of user config
  # into default config. Config class has no way of merging lists.
  # Types can be StorageClass names or DatasetType names
  disassembled:
    ExposureI: False
    ExposureF: False
    calexp: False
