dimensions:
  version: 0
  elements:

    instrument:
      doc: >
        An entity that produces observations.  An instrument defines a set of
        physical_filters and detectors and a numbering system for the exposures
        and visits that represent observations with it.
      link:
      - instrument

    abstract_filter:
      doc: >
        A filter that is not associated with a particular instrument.  An
        abstract filter can be used to relate similar physical filters, and
        is typically the filter associated with coadds.
      link:
      - abstract_filter

    physical_filter:
      dependencies:
        required:
        - instrument
        implied:
        - abstract_filter
      doc: >
        A filter associated with a particular instrument.  physical_filters are
        used to identify datasets that can only be associated with a single
        observation.
      link:
      - physical_filter

    detector:
      dependencies:
        required:
        - instrument
      doc: >
        A detector associated with a particular instrument (not an observation
        of that detector; that requires specifying an exposure or visit as
        well).
      link:
      - detector

    visit:
      dependencies:
        required:
        - instrument
        implied:
        - physical_filter
      doc: >
        A sequence of observations processed together, comprised of one or
        more exposures from the same instrument with the same pointing and
        physical_filter.
        The visit table contains metadata that is both meaningful only for
        science exposures and the same for all exposures in a visit.
      link:
      - visit
      hasRegion: true

    exposure:
      dependencies:
        required:
        - instrument
        implied:
        - visit
        - physical_filter
      doc: >
        An observation associated with a particular instrument.  All direct
        observations are identified with an exposure, but derived datasets
        that may be based on more than one exposure (e.g. multiple snaps) are
        typically identified with visits instead, even for instruments that
        don't have multiple exposures per visit.  As a result, instruments
        that don't have multiple exposures per visit will typically have visit
        entries that are essentially duplicates of their exposure entries.

        The exposure table contains metadata entries that are relevant for
        calibration exposures, and does not duplicate entries in visit that
        would be the same for all exposures within a visit.
      link:
      - exposure

    skypix:
      doc: >
        A pixel in a hierarchical decomposition of the sky (e.g. HTM, Q3C, or
        HEALPix; we will select and support just one, but which is TBD). Has
        no SQL representation; even a definition table is not necessary, given
        that the allowable values and the associated hasRegion regions are best
        computed on-the-fly.  skypix units are preferred to skymap (i.e.
        tract-patch) units for Datasets without any overlap regions (e.g.
        sharded reference catalogs).

        There are also considerable advantages to standardizing on just one
        level of the standard pixelization: if all skypix values are at a
        single level, they can be indexed using standard B-Trees and compared
        with simple equality comparison.  In contrast, comparing skypix values
        at different levels requires pixelization-specific bit-shifting
        operations and custom indexes, which are much harder to implement
        across multiple RDMSs.  As a result, we will (at least initially) try
        to define just a single level for all skypix values.  Our preliminary
        guess is that this level should have pixels be approximately (within a
        factor of ~4) of the size of a single detector on the sky.
      hasRegion:
        true
      link:
      - skypix

    skymap:
      doc: >
        A set of tracts and patches that subdivide the sky into rectangular
        regions with simple projections and intentional overlaps.
      link:
      - skymap

    tract:
      dependencies:
        required:
        - skymap
      doc: >
        A large rectangular region mapped to the sky with a single map
        projection, associated with a particular skymap.
      link:
      - tract
      hasRegion: true

    patch:
      dependencies:
        required:
        - skymap
        - tract
      doc: >
        A rectangular region within a tract.
      link:
      - patch
      hasRegion: true

    label:
      doc: >
        An arbitrary string value.  There is no SQL representation or
        constraint on the values a label can take.  Multiple labels are
        represented (by convention) by a comma-separated string.
      link:
      - label

    calibration_label:
      dependencies:
        required:
        - instrument
      doc: >
        A string label that maps to a date validity range for master
        calibration products.
      link:
      - calibration_label

    exposure_calibration_label_join:
      doc: >
        A many-to-many join table that relates exposure to calibration_label.

        This can and probably should be implemented as a view.
      lhs: [exposure]
      rhs: [calibration_label]

    visit_detector_region:
      doc: >
        A many-to-many join table that provides region information for
        visit-detector combinations.
      lhs: [visit]
      rhs: [detector]
      hasRegion: true
      asNeeded: true

    visit_detector_skypix_join:
      doc: >
        A spatial join table that relates visit+detector to skypix, also used
        as an intermediate when relating visit+detector to skymap DataUnits.

        Entries are expected to be calculated outside the database and
        added/updated whenever visit_detector_region is.

      lhs: [visit, detector]
      rhs: [skypix]

    visit_skypix_join:
      doc: >
        A spatial join table that relates visit to skypix, also used as an
        intermediate when relating visit to skymap DataUnits.

        This can and probably should be implemented as a trivial view on
        visit_detector_skypix_join.

      lhs: [visit]
      rhs: [skypix]
      summarizes: [visit_detector_skypix_join]

    patch_skypix_join:
      doc: >
        A spatial join table that relates patch to skypix, also used as an
        intermediate when relating patch to instrument DataUnits.

        Entries are expected to be calculated outside the database and
        added along with the patch itself.

      lhs: [patch]
      rhs: [skypix]

    tract_skypix_join:
      doc: >
        A spatial join table that relates tract to skypix, also used as an
        intermediate when relating tract to instrument DataUnits.

        This can and probably should be implemented as a trivial view on
        patch_skypix_join.

      lhs: [tract]
      rhs: [skypix]
      summarizes: [patch_skypix_join]

    visit_detector_patch_join:
      doc: >
        A spatial join table that relates visit+detector to patch via skypix.

        Should be implemented as a view; it may be materialized as long as it
        can be kept up to date when new visits or skymaps are added.

        If a database UDF is available to determine whether two regions
        overlap, we could include that in this view to refine the results.
        For now, we will assume that such a UDF is not available.

      lhs: [visit, detector]
      rhs: [patch]

    visit_patch_join:
      doc: >
        A spatial join table that relates visit to patch via skypix.

        Should be implemented as a view; it may be materialized as long as it
        can be kept up to date when new visits or skymaps are added.

        If a database UDF is available to determine whether two regions
        overlap, we could include that in this view to refine the results.
        For now, we will assume that such a UDF is not available.

      lhs: [visit]
      rhs: [patch]
      summarizes: [visit_detector_patch_join]

    visit_detector_tract_join:
      doc: >
        A spatial join table that relates visit+detector to tract via skypix.

        Should be implemented as a view; it may be materialized as long as it
        can be kept up to date when new visits or skymaps are added.

        If a database UDF is available to determine whether two regions
        overlap, we could include that in this view to refine the results.
        For now, we will assume that such a UDF is not available.

      lhs: [visit, detector]
      rhs: [tract]
      summarizes: [visit_detector_patch_join]

    visit_tract_join:
      doc: >
        A spatial join table that relates visit to tract via skypix.

        Should be implemented as a view; it may be materialized as long as it
        can be kept up to date when new visits or skymaps are added.

        If a database UDF is available to determine whether two regions
        overlap, we could include that in this view to refine the results.
        For now, we will assume that such a UDF is not available.

      lhs: [visit]
      rhs: [tract]
      summarizes:
        - visit_detector_patch_join
        - visit_detector_tract_join
        - visit_patch_join
