dimensions:
  version: 0
  skypix:
    common: htm7
    htm7:
      class: lsst.sphgeom.HtmPixelization
      level: 7
    htm9:
      class: lsst.sphgeom.HtmPixelization
      level: 9

  elements:
    instrument:
      doc: >
        An entity that produces observations.  An instrument defines a set of
        physical_filters and detectors and a numbering system for the exposures
        and visits that represent observations with it.
      keys:
      -
        name: name
        type: string
        length: 16
      metadata:
      -
        name: visit_max
        type: int
        doc: >
          Maximum value for the 'visit' field for visits associated with
          this instrument (exclusive).
      -
        name: exposure_max
        type: int
        doc: >
          Maximum value for the 'exposure' field for exposures associated with
          this instrument (exclusive).
      -
        name: detector_max
        type: int
        doc: >
          Maximum value for the 'detector' field for detectors associated with
          this instrument (exclusive).
      cached: true

    abstract_filter:
      doc: >
        A filter that is not associated with a particular instrument.  An
        abstract filter can be used to relate similar physical filters, and
        is typically the filter associated with coadds.
      keys:
      -
        name: name
        type: string
        length: 16
      view_of: physical_filter

    physical_filter:
      doc: >
        A filter associated with a particular instrument.  physical_filters are
        used to identify datasets that can only be associated with a single
        observation.
      keys:
      -
        name: name
        type: string
        length: 32
      requires:
      - instrument
      implies:
      - abstract_filter
      cached: true

    subfilter:
      doc: >
        A mathematical division of an abstract_filter. Subfilters are used to
        model wavelength-dependent effects such as differential chromatic
        refraction.
      keys:
      -
        name: name
        type: string
        length: 18
      implies:
      - abstract_filter
      cached: true

    detector:
      doc: >
        A detector associated with a particular instrument (not an observation
        of that detector; that requires specifying an exposure or visit as
        well).
      keys:
      -
        name: id
        type: int
      -
        name: full_name
        type: string
        length: 32
      requires: [instrument]
      metadata:
      -
        name: name_in_raft
        type: string
        length: 32
      -
        name: raft
        type: string
        length: 32
        doc: >
          A string name for a group of detectors with an instrument-dependent
          interpretation.
      -
        name: purpose
        type: string
        length: 32
        doc: >
          Role of the detector; typically one of "SCIENCE", "WAVEFRONT",
          or "GUIDE", though instruments may define additional values.
      cached: true

    visit:
      doc: >
        A sequence of observations processed together, comprised of one or
        more exposures from the same instrument with the same pointing and
        physical_filter.
        The visit table contains metadata that is both meaningful only for
        science exposures and the same for all exposures in a visit.
      keys:
      -
        name: id
        type: int
      -
        name: name
        type: string
        length: 64
      requires: [instrument]
      implies: [physical_filter]
      spatial: true
      temporal: true
      metadata:
      -
        name: exposure_time
        type: float
        doc: >
          The total exposure time of the visit in seconds.  This should
          be equal to the sum of the exposure_time values for all
          constituent exposures (i.e. it should not include time between
          exposures).
      -
        name: seeing
        type: float
        doc: >
          Average seeing, measured as the FWHM of the Gaussian with the same
          effective area (arcsec).

    exposure:
      doc: >
        An observation associated with a particular instrument.  All direct
        observations are identified with an exposure, but derived datasets
        that may be based on more than one exposure (e.g. multiple snaps) are
        typically identified with visits instead, even for instruments that
        don't have multiple exposures per visit.  As a result, instruments
        that don't have multiple exposures per visit will typically have visit
        entries that are essentially duplicates of their exposure entries.

        The exposure table contains metadata entries that are relevant for
        calibration exposures, and does not duplicate entries in visit that
        would be the same for all exposures within a visit.
      keys:
      -
        name: id
        type: int
      -
        name: name
        type: string
        length: 64
      requires: [instrument]
      implies: [visit, physical_filter]
      temporal: true
      metadata:
      -
        name: exposure_time
        type: float
        doc: Duration of the exposure with shutter open (seconds).
      -
        name: dark_time
        type: float
        doc: Duration of the exposure with shutter closed (seconds).
      -
        name: observation_type
        type: string
        length: 64

    skymap:
      doc: >
        A set of tracts and patches that subdivide the sky into rectangular
        regions with simple projections and intentional overlaps.
      keys:
      -
        name: name
        type: string
        length: 64
      -
        name: hash
        type: hash
        nbytes: 40
        doc: >
          A hash of the skymap's parameters.
      metadata:
      - name: tract_max
        type: int
        doc: >
          Maximum ID for tracts in this skymap, exclusive.
      - name: patch_nx_max
        type: int
        doc: >
          Number of patches in the x direction in each tract.
      - name: patch_ny_max
        type: int
        doc: >
          Number of patches in the y direction in each tract.
      cached: true

    tract:
      doc: >
        A large rectangular region mapped to the sky with a single map
        projection, associated with a particular skymap.
      keys:
      -
        name: id
        type: int
      requires: [skymap]
      spatial: true

    patch:
      doc: >
        A rectangular region within a tract.
      keys:
      -
        name: id
        type: int
      requires: [skymap, tract]
      spatial: true
      metadata:
      -
        name: cell_x
        type: int
        nullable: false
        doc: >
          Which column this patch occupies in the tract's grid of patches.
      -
        name: cell_y
        type: int
        nullable: false
        doc: >
          Which row this patch occupies in the tract's grid of patches.

    calibration_label:
      doc: >
        A string label that maps to a date validity range for master
        calibration products.
      keys:
      -
        name: name
        type: string
        length: 128
      requires: [instrument]
      temporal: true

    visit_detector_region:
      doc: >
        A many-to-many join table that provides region information for
        visit-detector combinations.
      requires: [visit, detector]
      spatial: true

  packers:
    visit_detector:
      fixed: [instrument]
      dimensions: [instrument, visit, detector]
      cls: lsst.daf.butler.instrument.ObservationDimensionPacker
    exposure_detector:
      fixed: [instrument]
      dimensions: [instrument, exposure, detector]
      cls: lsst.daf.butler.instrument.ObservationDimensionPacker
    tract_patch:
      fixed: [skymap]
      dimensions: [skymap, tract, patch]
      cls: lsst.skymap.packers.SkyMapDimensionPacker
    tract_patch_abstract_filter:
      fixed: [skymap]
      dimensions: [skymap, tract, patch, abstract_filter]
      cls: lsst.skymap.packers.SkyMapDimensionPacker
