# Default with a sqlLite registry
registry:
  clsMap:
    sql: lsst.daf.butler.registries.sqlRegistry.SqlRegistry
    sqlite: lsst.daf.butler.registries.sqliteRegistry.SqliteRegistry
    postgresql: lsst.daf.butler.registries.postgresqlRegistry.PostgreSqlRegistry
    oracle: lsst.daf.butler.registries.oracleRegistry.OracleRegistry
  db: 'sqlite:///:memory:'
  skypix:
    cls: lsst.sphgeom.HtmPixelization
    level: 7
  dataIdPackers:
    visit_detector:
      given: [instrument]
      required: [instrument, visit, detector]
      cls: lsst.daf.butler.instrument.ObservationDataIdPacker
      parameters:
        instrument: instrument.instrument
        obsMax: instrument.visit_max
        detectorMax: instrument.detector_max
    exposure_detector:
      given: [instrument]
      required: [instrument, exposure, detector]
      cls: lsst.daf.butler.instrument.ObservationDataIdPacker
      parameters:
        instrument: instrument.instrument
        obsMax: instrument.exposure_max
        detectorMax: instrument.detector_max
    tract_patch:
      given: [skymap]
      required: [skymap, tract, patch]
      cls: lsst.skymap.packers.SkyMapDataIdPacker
      parameters:
        skymap: skymap.skymap
        tractMax: skymap.tract_max
        patchNxMax: skymap.patch_nx_max
        patchNyMax: skymap.patch_ny_max
    tract_patch_abstract_filter:
      given: [skymap]
      required: [skymap, tract, patch, abstract_filter]
      cls: lsst.skymap.packers.SkyMapDataIdPacker
      parameters:
        skymap: skymap.skymap
        tractMax: skymap.tract_max
        patchNxMax: skymap.patch_nx_max
        patchNyMax: skymap.patch_ny_max
