schema:
  version: 0
  tables:
    dataset:
      columns:
      -
        name: dataset_id
        type: int
        primaryKey: true
        nullable: false
        autoincrement: true
        doc: >
          A unique autoincrement field used the primary key for dataset.
      -
        name: dataset_type_name
        type: string
        length: 128
        nullable: false
        doc: >
          The name of the DatasetType associated with this dataset; a
          reference to the dataset_type table.
      -
        name: run_id
        type: int
        nullable: false
        doc: >
          The id of the run that produced this dataset, providing access to
          coarse provenance information.
      -
        name: quantum_id
        type: int
        doc: >
          The id of the quantum that produced this dataset, providing access
          to fine-grained provenance information.
          may be null for datasets not produced by running a supertask.
      -
        name: dataset_ref_hash
        type: hash
        nbytes: 32
        nullable: false
        doc: >
          Secure hash of the data ID (i.e. dimension link values) and
          dataset_type_name.
      foreignKeys:
      -
        table: dataset_type
        source: dataset_type_name
        target: dataset_type_name
      -
        table: run
        source: run_id
        target: execution_id
      -
        table: quantum
        source: quantum_id
        target: execution_id
        onDelete: SET NULL

    dataset_composition:
      doc: >
        A self-join table that relates components of a dataset to their
        parent.
      columns:
      -
        name: parent_dataset_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          Link to the Dataset entry for the parent/composite dataset.
      -
        name: component_dataset_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          Link (with component_dataset_id) to the Dataset entry for a
          child/component dataset.
      -
        name: component_name
        type: string
        length: 32
        nullable: false
        doc: >
          Name of this component within this composite.
      foreignKeys:
      -
        table: dataset
        source: parent_dataset_id
        target: dataset_id
        onDelete: CASCADE
      -
        table: dataset
        source: component_dataset_id
        target: dataset_id
        onDelete: CASCADE

    dataset_type:
      doc: >
        A Table containing the set of registered DatasetTypes and their
        StorageClasses.
      columns:
      -
        name: dataset_type_name
        type: string
        length: 128
        primaryKey: true
        nullable: false
        doc: >
          Globally unique name for this DatasetType.
      -
        name: storage_class
        type: string
        length: 64
        nullable: false
        doc: >
          Name of the StorageClass associated with this DatasetType.  All
          registries must support the full set of standard StorageClasses,
          so the set of allowed StorageClasses and their properties is
          maintained in the registry Python code rather than the database.

    dataset_type_dimensions:
      doc: >
        A Definition table indicating which dimension link fields in Dataset
        are non-NULL for Datasets with this DatasetType.
      columns:
      -
        name: dataset_type_name
        type: string
        length: 128
        nullable: false
        doc: >
          The name of the DatasetType.
      -
        name: dimension_name
        type: string
        length: 32
        nullable: false
        doc: >
          The name of a Dimension associated with this DatasetType.
      foreignKeys:
      -
        table: dataset_type
        source: dataset_type_name
        target: dataset_type_name

    dataset_type_metadata:
      doc: >
        A table the indicating the Metadata tables that have entries for
        Datasets with this DatasetType.
      columns:
      -
        name: dataset_type_name
        type: string
        length: 128
        nullable: false
        doc: >
          The name of the DatasetType.
      -
        name: metadata_name
        type: string
        length: 32
        nullable: false
        doc: >
          The name of a Metadata table that has a record for every Dataset
          entry with this DatasetType.
      foreignKeys:
      -
        table: dataset_type
        source: dataset_type_name
        target: dataset_type_name

    dataset_collection:
      doc: >
          A table that associates Dataset records with Collections, which are
          implemented simply as string tags.
      columns:
      -
        name: dataset_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          Link to a unique record in the dataset table.
      -
        name: dataset_ref_hash
        type: hash
        nbytes: 32
        nullable: false
        doc: >
          Secure hash of the data ID (i.e. dimension link values) and
          dataset_type_name.
      -
        name: collection
        type: string
        length: 128
        primaryKey: true
        nullable: false
        doc: >
          Name of a Collection with which this Dataset is associated.
      foreignKeys:
      -
        table: dataset
        source: dataset_id
        target: dataset_id
        onDelete: CASCADE
      unique:
      - [dataset_ref_hash, collection]

    execution:
      doc: >
        A table whose entries represent any step in a production.
      columns:
      -
        name: execution_id
        type: int
        primaryKey: true
        nullable: false
        autoincrement: true
        doc: >
          A unique autoincrement field used as the primary key for
          Execution.
      -
        name: start_time
        type: datetime
        nullable: true
        doc: >
          The start time for the Execution.  May have a different
          interpretation for different kinds of Execution.
      -
        name: end_time
        type: datetime
        nullable: true
        doc: >
          The end time for the Execution.  May have a different
          interpretation for different kinds of Execution.
      -
        name: host
        type: string
        length: 64
        nullable: true
        doc: >
          The system on which the Execution was run.  May have a different
          interpretation for different kinds of Execution.

    run:
      doc: >
        A table used to capture coarse provenance for all Datasets. For
        Datasets produced by SuperTask Pipelines, a Run represents a single
        execution of a single Pipeline. Each run record is uniquely
        associated with an execution record.
      columns:
      -
        name: execution_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          A unique integer identifier for this Run, which
          is also the execution_id for an associated execution record.
      -
        name: collection
        type: string
        length: 128
        doc: >
          A Collection name with which all Datasets in this Run are initially
          associated, also used as a human-readable name for this Run.
      foreignKeys:
      -
        table: execution
        source: execution_id
        target: execution_id
        onDelete: CASCADE

    quantum:
      doc: >
        A table used to capture fine-grained provenance for Datasets
        produced by SuperTasks. Each Quantum record is uniquely associated
        with an execution record.
      columns:
      -
        name: execution_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          A unique integer identifier for this Quantum,
          which is also the execution_id for an associated execution record.
      -
        name: task
        type: string
        length: 256
        doc: >
          Fully-qualified name of the SuperTask that executed this quantum.
      -
        name: run_id
        type: int
        doc: >
          Link to the Run this Quantum is a part of.
      foreignKeys:
      -
        table: run
        source: run_id
        target: execution_id
        onDelete: CASCADE
      -
        table: execution
        source: execution_id
        target: execution_id
        onDelete: CASCADE

    dataset_consumers:
      doc: >
        A table relating Quantum records to the Datasets they used as inputs.
      columns:
      -
        name: quantum_id
        type: int
        nullable: false
        doc: >
          A link to the associated Quantum.
      -
        name: dataset_id
        type: int
        nullable: false
        doc: >
          A link to the associated Dataset.
      -
        name: actual
        type: bool
        nullable: false
        doc: >
          Whether the Dataset was actually used as an input by the Quantum
          (as opposed to just predicted to be used during preflight).
      foreignKeys:
      -
        table: quantum
        source: quantum_id
        target: execution_id
        onDelete: CASCADE
      -
        table: dataset
        source: dataset_id
        target: dataset_id
        onDelete: CASCADE

    dataset_storage:
      doc: >
        A table that provides information on whether a Dataset is stored in
        one or more Datastores.  The presence or absence of a record in this
        table itself indicates whether the Dataset is present in that
        Datastore.
      columns:
      -
        name: dataset_id
        type: int
        primaryKey: true
        nullable: false
        doc: >
          Link to the dataset table.
      - name: datastore_name
        type: string
        length: 256
        primaryKey: true
        nullable: false
        doc: >
          Name of the Datastore this entry corresponds to.
      foreignKeys:
      -
        table: dataset
        source: dataset_id
        target: dataset_id
